# Generated by Django 4.2.30 on 2026-06-05 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recomendador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoIaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('CHAT', 'Chat Conversacional RAG'), ('RECOMENDACAO', 'Recomendacao Semantica')], max_length=20, verbose_name='Tipo de Servico')),
                ('entrada', models.JSONField(verbose_name='Dados de Entrada')),
                ('saida', models.JSONField(verbose_name='Dados de Saida')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Requisicao de IA',
                'verbose_name_plural': 'Logs de Requisicao de IA',
                'ordering': ['-timestamp'],
            },
        ),
    ]
